./scripts/nccl-tests/testcase_agg_iters.sh
./scripts/nccl-tests/testcase_average.sh
./scripts/nccl-tests/testcase_blocking.sh
./scripts/nccl-tests/testcase_cudagraph.sh
./scripts/nccl-tests/testcase_datatype.sh
./scripts/nccl-tests/testcase_local_register.sh
./scripts/nccl-tests/testcase_max_bytes.sh
./scripts/nccl-tests/testcase_min_bytes.sh
./scripts/nccl-tests/testcase_ngpu_thread.sh
./scripts/nccl-tests/testcase_nprocs.sh
./scripts/nccl-tests/testcase_nthreads.sh
./scripts/nccl-tests/testcase_num_iters.sh
./scripts/nccl-tests/testcase_op.sh
./scripts/nccl-tests/testcase_output_file.sh
./scripts/nccl-tests/testcase_paralell_init.sh
./scripts/nccl-tests/testcase_report_cputime.sh
./scripts/nccl-tests/testcase_report_timestanmps.sh
./scripts/nccl-tests/testcase_result_check.sh
./scripts/nccl-tests/testcase_root.sh
./scripts/nccl-tests/testcase_run_cycles.sh
./scripts/nccl-tests/testcase_step_factor.sh
./scripts/nccl-tests/testcase_step_inc.sh
./scripts/nccl-tests/testcase_timeout.sh
./scripts/nccl-tests/testcase_warmup_iters.sh
./scripts/nccl-tests/testcase_workload.sh
